USE chadlister_db;

INSERT INTO ads (title, description, price, image_url) VALUES ('Sega Dreamcast', 'Barely beat up but working Dreamcast', 500, 'https://m.media-amazon.com/images/I/61y6pFPJA8L._SL1040_.jpg'),
                                                              ('1st Edition Dragonite', 'You could be the proud owner of this PSA 10 Dragonite', 3000, 'https://images.stockx.com/images/Dark-Dragonite-2000-Pokemon-Rocket-1st-Edition-22-PSA.jpg?fit=fill&bg=FFFFFF&w=480&h=320&fm=jpg&auto=compress&dpr=2&trim=color&updated_at=1620851282&q=80'),
                                                              ('Atomic Purple N64 controller', 'Bring back those childhood feels with this classic control', 100, 'https://doublejumpvideogames.com/wp-content/uploads/2021/11/nintendo_atomic_purple_controller.jpg'),
                                                              ('Gaming PC', 'Whats money to a real gamer? Blow it on this powerful gaming beast.', 7000, 'https://www.windowscentral.com/sites/wpcentral.com/files/styles/large/public/field/image/2021/02/corsair-icue-5000x-rgb-fans-01.jpg'),
                                                              ('Xbox Ekkis Series Ekkis', 'Get this little powerhouse for your home entertainment', 550, 'https://compass-ssl.xbox.com/assets/83/53/83534a33-0998-43dc-915a-4ec0a686d679.jpg?n=10202018_Panes-3-up-1400_Hero-SX_570x570.jpg'),
                                                              ('Nintendo Gameboy Color', 'Play all your old Pokemon games the way the were orginally played.', 200, 'https://i.ebayimg.com/images/g/-4cAAOSwn4tdqrbz/s-l400.jpg'),
                                                              ('2013 Shiny Magikarp Plush', 'Human Sized plush for people who love Magikarp', 2500, 'https://discord.com/channels/@me/943206689660887070/973615525940846613'),
                                                              ('Hyper Ekkis Ekkis Ekkis Headset', 'Take your gaming to the next level with this exquisite headset chosen by the pros', 300, 'https://i.pcmag.com/imagery/reviews/06g43wkwvluqEmcw4BKLE8s-3.fit_scale.size_760x427.v1569471699.jpg'),
                                                              ('Gaming Monitor', 'See the heads your clicking with this 144hz monitor', 800, 'https://webobjects2.cdw.com/is/image/CDW/6219362?wid=784&hei=477&resMode=bilin&fit=fit,1'),
                                                              ('Playstation 5', 'Play all the great Playstation Exclusive titles', 550, 'https://images.immediate.co.uk/production/volatile/sites/3/2020/08/playstation-5-77d37a0.jpg?quality=90&resize=620,413');
